// .BOS/Taskfile.yaml: the workshop's own procedures, pointing at this BOS installation.
import { CLI } from "../../core/self.mjs";

export const workshopTaskfile = () => `# yaml-language-server: $schema=https://taskfile.dev/schema.json
# workshop procedures, generated by BOS bootstrap; edit freely
version: '3'

vars:
  BOS: node ${CLI}

tasks:
  status:
    desc: show the state of this workshop
    cmds: ['{{.BOS}} workshop status']
  open:
    desc: open the workshop (bootstrap missing areas, record opening)
    cmds: ['{{.BOS}} workshop open']
  close:
    desc: close the workshop (capture ttystory, record closing)
    cmds: ['{{.BOS}} workshop close']
`;
