// A draft SKILL.md for each model, from its glossary page and its class.
import { firstSentence, section, title } from "./glossary.mjs";

const quote = (text) => `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

export function composeSkill({ Model, type, page }) {
  const what = section(page, "What it is") || "[`TODO`] no glossary page yet";
  const where = section(page, "Where") || "[`TODO`]";
  const hangs = Object.entries(Model.submodules).map(([name, Sub]) => `- \`${name}\` → \`${Sub.dirname}/\``);
  const description = `${firstSentence(what)} Use when creating, finding or handling a BOS ${type}, or when the user mentions a ${type}.`;
  return [
    "---",
    `name: bos-${type}`,
    `description: ${quote(description)}`,
    "---",
    "",
    `# ${title(page) ?? type} (BOS)`,
    "",
    `> Draft generated by \`bos skills\` from \`docs/glossary/${type}.md\` and \`src/models/${type}/\`.`,
    "> Grow it by hand: it is never overwritten.",
    "",
    "## What it is",
    "",
    what,
    "",
    "## Where",
    "",
    where,
    ...(hangs.length ? ["", "## Submodules", "", ...hangs] : []),
    "",
    "## Handling",
    "",
    `[\`TODO\`] procedures and commands for a ${type}.`,
    "",
    "## References",
    "",
    `- [glossary](../../docs/glossary/${type}.md)`,
    `- [model](../../src/models/${type}/class.mjs)`,
    "",
  ].join("\n");
}

export const composeSkills = (context) => {
  context.skills = context.models.map((model) => ({ type: model.type, name: `bos-${model.type}`, text: composeSkill(model) }));
};
