// The BOS elements as code. Each class mirrors one page of docs/glossary/.
// Areas have a fixed dirname and are created by bootstrap; artefacts are named freely.
import { appendFileSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";

import { BasicModel } from "../core/basic-model.mjs";
import { CLI } from "../core/self.mjs";

export const WORKSHOP_DIRNAME = "__WORKSHOP";

// setternet roles a workshop can give its host (glossary: host-role.md)
export const HOST_ROLES = {
  "masters-outpost": "remote management of every BOS host in the setternet (Posterunek Mistrza)",
  "forging-point": "development, compilation and similar work (Punkt Kuźniczy)",
  "trial-hall": "virtual machines and testing (Sala Prób)",
  "market-stall": "publication only: automatic posts and announcements (Kram Targowy)",
  "canon-monolith": "the one master archive of all projects (Monolit Kanonu)",
  "side-catacomb": "archive dedicated to one function (Katakumb Poboczny)",
};

// ---------------------------------------------------------------- .BOS internals

export class Setup extends BasicModel {
  static type = "setup";
  static dirname = "setup";
}

export class Data extends BasicModel {
  static type = "data";
  static dirname = "data";
}

export class Nests extends BasicModel {
  static type = "nestrelm";
  static dirname = "nests";
  static descriptors = {
    ".index.json": () => ({ nests: {} }),
    ".manifest.json": () => ({ files: {} }),
  };
}

class Ttystories extends BasicModel {
  static type = "ttystories";
  static dirname = "ttystories";
}

class Logs extends BasicModel {
  static type = "logs";
  static dirname = "logs";
}

class Manifests extends BasicModel {
  static type = "manifests";
  static dirname = "manifests";
}

// not needed to launch; appears with the first recorded event
export class Storylines extends BasicModel {
  static type = "storylines";
  static dirname = "storylines";
  static mandatory = false;
  static children = [Ttystories, Logs, Manifests];
  static descriptors = {
    "metadata.json": (element, context) => ({
      origin: {
        host: context.env?.host ?? null,
        user: context.env?.user ?? null,
        unixusat: context.env?.unixusat ?? Date.now(),
        createdBy: "blacksmith-organizing-system",
      },
    }),
  };

  // one JSON line per event: opening, closing, git hooks, ...
  record(event, context = {}) {
    const entry = { unixusat: Date.now(), host: context.env?.host ?? null, ...event };
    if (!context.dryRun) appendFileSync(this.file("logs", "workshop.jsonl"), JSON.stringify(entry) + "\n");
    return entry;
  }

  ttystoryName(context) {
    return `ttystory-${context.env.host}-${context.env.unixusat}.txt`;
  }
}

export class System extends BasicModel {
  static type = "system";
  static dirname = ".BOS";
  static children = [Setup, Data, Nests, Storylines];
  static descriptors = {
    "workshop.json": (element, context) => context.config ?? {},
    "Taskfile.yaml": () => [
      "# yaml-language-server: $schema=https://taskfile.dev/schema.json",
      "# workshop procedures, generated by BOS bootstrap; edit freely",
      "version: '3'",
      "",
      "vars:",
      `  BOS: node ${CLI}`,
      "",
      "tasks:",
      "  status:",
      "    desc: show the state of this workshop",
      "    cmds: ['{{.BOS}} status']",
      "  open:",
      "    desc: open the workshop (bootstrap missing areas, record opening)",
      "    cmds: ['{{.BOS}} open']",
      "  close:",
      "    desc: close the workshop (capture ttystory, record closing)",
      "    cmds: ['{{.BOS}} close']",
      "",
    ].join("\n"),
  };
}

// ---------------------------------------------------------------- crafting areas

export class Devarmory extends BasicModel {
  static type = "devarmory";
  static dirname = "devarmory";
  // tools listed with checksums, so missing or damaged ones can be found (format still open)
  static descriptors = { "manifest.json": () => ({ tools: {}, files: {} }) };
}

export class Forge extends BasicModel {
  static type = "forge";
  static dirname = "forge";

  scopes() {
    return listDirs(this.path).map((path) => new Scope(path, this));
  }
}

class Scrapnotes extends BasicModel {
  static type = "scrapnotes";
  static dirname = "scrapnotes";
}

export class Craftbook extends BasicModel {
  static type = "craftbook";
  static dirname = "craftbook";
  static children = [Scrapnotes];
}

export class Archive extends BasicModel {
  static type = "archive";
  static dirname = "archive";
}

export class Workshop extends BasicModel {
  static type = "workshop";
  static dirname = WORKSHOP_DIRNAME;
  static children = [System, Devarmory, Forge, Craftbook, Archive];

  get system() { return new System(this.file(System.dirname), this); }
  get storylines() { return new Storylines(this.file(System.dirname, Storylines.dirname), this.system); }
}

// ---------------------------------------------------------------- artefacts

// private repository holding a family of projects, shemes and one throwbox
export class Scope extends BasicModel {
  static type = "scope";
}

export class Project extends BasicModel {
  static type = "project";
  // what every project is expected to carry (glossary: project.md)
  static anatomy = {
    "README.md": "what it is and how to use it",
    "LICENSE": "terms of use",
    "AGENTS.md": "instructions for AI agents (CLAUDE.md imports it)",
    "Taskfile.yml": "procedures: build, test, run",
    "src": "source code",
    "docs": "documentation",
    "tests": "tests",
    ".github": "community files and CI workflows",
  };

  anatomyCheck() {
    const present = [];
    const missing = [];
    for (const part of Object.keys(Project.anatomy)) {
      (new BasicModel(this.file(part)).exists() ? present : missing).push(part);
    }
    return { present, missing };
  }
}

export class Sheme extends BasicModel {
  static type = "sheme";
}

export class Throwbox extends BasicModel {
  static type = "throwbox";
  static dirname = "throwbox";
}

export class Sarcophag extends BasicModel {
  static type = "sarcophag";
}

export class Exhibit extends BasicModel {
  static type = "exhibit";
}

export class Craftset extends BasicModel {
  static type = "craftset";
  static descriptors = {
    ".omnis.toml": () => "# [TODO] contents of .omnis.toml are not defined yet\n",
    "metadata.json": (element) => ({ name: element.name, created: Date.now() }),
    "manifest.json": () => ({ files: {} }),
    "Taskfile.yaml": () => "version: '3'\n\ntasks: {}\n",
  };
}

export const ELEMENTS = Object.fromEntries(
  [Workshop, System, Setup, Data, Nests, Storylines, Devarmory, Forge, Craftbook, Archive,
    Scope, Project, Sheme, Throwbox, Sarcophag, Exhibit, Craftset].map((Model) => [Model.type, Model])
);

function listDirs(path) {
  if (!existsSync(path)) return [];
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("."))
    .map((entry) => join(path, entry.name));
}
